version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    groups:
      nx:
        patterns:
          - nx
          - '@nx/*'
      nestjs:
        patterns:
          - '@nestjs/*'
      react-next:
        patterns:
          - next
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
    commit-message:
      prefix: deps
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: America/Sao_Paulo
    commit-message:
      prefix: ci
      include: scope
